# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

concurrency: development

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      CI: false
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present -- --no-warnings

  # test:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         cache: 'npm'
  #     - run: npm ci
  #     - name: Run Tests
  #       run: npm test -- --coverage
  #     - name: Setup Pages
  #       if: github.ref == 'refs/heads/main'
  #       uses: actions/configure-pages@v3
  #     - name: Upload Artifact
  #       if: github.ref == 'refs/heads/main'
  #       uses: actions/upload-pages-artifact@v1
  #       with:
  #         path: "./coverage"

  deploy:
    # if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: development
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
