name: Prod CI

concurrency: prod

on:
  push:
    branches: ["main"]

jobs:
  test-build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      CI: false
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present -- --no-warnings

  
  deploy-on-main:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: test-build
    environment: prod

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: SSH deploy to remote server
        run: |
          ssh ${{ secrets.REMOTE_SERVER_USERNAME }}@${{ secrets.REMOTE_SERVER_ADDRESS }}
          cd /home/debian/app/frontend
          git pull origin main
          npm install
          npm run build
