name: Prod CI

concurrency: prod

on:
  push:
    branches: ["main"]

jobs:
  test-build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      CI: false
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present -- --no-warnings

  
  build-on-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test-build
    environment: prod
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.PROD_RENDER_API_KEY }}
